# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-16 13:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20170616_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='invite_code',
            field=models.CharField(default='', max_length=8, unique=True),
            preserve_default=False,
        ),
    ]
